services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    env_file:
      - ./.env.local
    volumes:
      - ./app:/app
    command: yarn dev --host
    ports:
      - "3000:3000"