services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    tty: true
    env_file:
      - ./.env.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"